"""empty message

Revision ID: 7810d662752a
Revises: 09d22ed00240
Create Date: 2025-07-12 09:41:28.962865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7810d662752a'
down_revision = '09d22ed00240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('live_site_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('collaborators')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collaborators', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.drop_column('github_url')
        batch_op.drop_column('live_site_url')
        batch_op.drop_column('client_name')

    op.drop_table('collaborators')
    # ### end Alembic commands ###
