"""empty message

Revision ID: e778856e9258
Revises: 396921f5dd5d
Create Date: 2025-07-11 15:41:24.208177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e778856e9258'
down_revision = '396921f5dd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tech_tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ai_used', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ai_desc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('project_value', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('case_study_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('collaborators', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('collaborators')
        batch_op.drop_column('case_study_url')
        batch_op.drop_column('project_value')
        batch_op.drop_column('ai_desc')
        batch_op.drop_column('ai_used')
        batch_op.drop_column('role')
        batch_op.drop_column('tech_tags')
        batch_op.drop_column('project_type')
        batch_op.drop_column('poster_filename')
        batch_op.drop_column('video_filename')
        batch_op.drop_column('description')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
